[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88
target-version = "py38"
exclude = ["migrations"]
select = ["E", "F", "I"]  # Error, Formatting, Imports
fix = true
